apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: devx-helloworld-springboot-r3fyg
    backstage.io/kubernetes-id: devx-helloworld-springboot-r3fyg
  name: devx-helloworld-springboot-r3fyg
  namespace: '{{ .Values.config.namespace }}'
spec:
  replicas: 1
  selector:
    matchLabels:
      app: devx-helloworld-springboot-r3fyg
  strategy: {}
  imagePullSecrets:
    - name: artifact-registry
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: devx-helloworld-springboot-r3fyg
    spec:
      containers:
      - image: uswest2fpmt.jfrog.io/default-docker-virtual/vad1mo/hello-world-rest
        imagePullPolicy: IfNotPresent
        name: devx-helloworld-springboot-r3fyg
        resources: {}
        ports:
          - containerPort: 5050 
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 5050
          periodSeconds: 5
      imagePullSecrets:
        - name: artifact-registry
status: {}
